### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by choucavalier** [vedpatil611/low-battery-warning#3]
Running the latest version (freshly installed from AUR) results in a segmentation fault.

I have no other information because the software is not providing any log

**Comment by choucavalier** [comment]
I found the issue, while debugging with GDB.

The code assumes the battery to be `BAT1` but my battery is `BAT0`. Therefore the code is attempting to read a file `/sys/class/power_supply/BAT1` that does not exist.

I think the code should be extended in order to attempt reading `BAT0` and `BAT1`

**Comment by vedpatil611** [comment]
If you want you can create a fork and change BAT1 to BAT0 to match your system or give me time till sunday to fix this.

**Comment by vedpatil611** [comment]
This was resolved in commit e01998a56fa3daebb90db4935db6ae1942741b74
